name: planar_robot
has_entropy: False
dim: 10
num_goals: 1
fn:
  _target_: targets.planar_robot.PlanarRobot
  dim: ${target.dim}
  num_goals: ${target.num_goals}
  log_Z:
  can_sample: False
  sample_bounds: None

# Experiment-specific algorithm parameters
# ----------------------------------------

mfvi: # Gaussian Mean Field Variational Inference
  initial_scale: 1.
  step_size: 1e-3

gmmvi: # Gaussian Mixture Model Variational Inference
  initial_scale: 1.

nfvi: # Normalizing Flow Variational Inference
  initial_scale: 2.
  step_size: 1e-3

hmc:  # Hamilton Monte Carlo
  hmc_step_size: [0.001,0.01] #[0.01,0.1]

smc: # Sequential Monte Carlo Sampler
  initial_scale: 2

flow_transport: # Flow Transport Methods (AFT/CRAFT)
  initial_scale: 1.
  step_size: 1e-3

fab: # Flow Annealed Importance Sampling Bootstrap
  initial_scale: 2
  step_size: 0.0001
ud_langevin:  # Underdamped Langevin Methods (UHA/LDVI)
  max_diffusion: 1.
  initial_scale: 1.
  step_size: 5e-4

od_langevin:  # Overdamped Langevin Methods (ULA/MCD)
  max_diffusion: 1.
  initial_scale: 1.
  step_size: 5e-4

cmcd: # CMCD
  initial_scale: 2 #0.1
  max_diffusion: 0.03
  step_size: 1e-4

pis: # Path Integral Sampler
  step_size: 0.00001
  max_diffusion: 0.3

dis: # DIS
  initial_scale: 2
  step_size: 0.001
  max_diffusion: 0.3

scds:
  initial_scale: 1.
  step_size: 5e-4

dds: # Denoising Diffusion Sampler
  initial_scale: 2
  step_size: 0.001
  max_diffusion: 0.3

gfn: # Generative Flow Networks
  max_diffusion: 4. # Divided by 4 roughly gives the initial scale
  step_size: 5e-4

gbs:  # General Bridge Sampler
  max_diffusion: 1.
  initial_scale: 1.
  step_size: 5e-4

all: # Parameters that are shared between all algorithms
  batch_size: 1024
